version: "3"

services:
  postgres:
    image: "postgres:14.5"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amd

    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#       - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/autome8_oscweb.sql:/docker-entrypoint-initdb.d/autome8_oscweb.sql


# version: '3.7'

# services:
#   db:
#     image: mysql:latest
#     container_name: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: amd
#       MYSQL_USER: root
#       # MYSQL_PASSWORD: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./sql/autome8_oscweb.sql:/docker-entrypoint-initdb.d/autome8_oscweb.sql
